### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by RetroJimmyX** [orionrobots/python_usb_robot_arm#11]
I am getting the message regarding line 67 in the __init__.py file which is self.dev.set_configuration()

the error is:

AttributeError: 'NoneType' object has no attribute 'set_configuration'

I looked through the code and couldn't find this set_configuration method anywhere.

Please could you advise? Thanks in advance.

**Comment by namllihs** [comment]
It could be that your arm is not switched on or the batteries are dead.

**Comment by dannystaple** [comment]
I've added an exception to check that it has found the arm before trying set_configuration.

**Comment by RetroJimmyX** [comment]
Thank you. The arm seems to be like to be switched on and then plugged in via USB.
