### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by guykirs** [orionrobots/python_usb_robot_arm#3]
-raspberry pi  - - os/Buster  
Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux

Collecting git+https://github.com/orionrobots/python_usb_robot_arm
  Cloning https://github.com/orionrobots/python_usb_robot_arm to /tmp/pip-req-build-52ql290l
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-52ql290l/setup.py", line 9, in <module>
        long_description=open('README.txt').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-52ql290l/

**Comment by dannystaple** [comment]
Ah - that will be a change I'd made. I've made a fix to that now.

**Comment by dannystaple** [comment]
@guykirs has reported that this is now working. I will also add some workflow actions to automate detecting problems like that.
